# Generated by Django 2.2.1 on 2019-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('dueDate', models.DateField()),
            ],
        ),
    ]
